defmodule TestFixtures do
  def sample_xml do
    """
    <?xml version="1.0" encoding="ISO-8859-1"?> \r\n<?xml-stylesheet href="latest_ob.xsl" type="text/xsl"?>\r\n<current_observation version="1.0"\r\n\t xmlns:xsd="http://www.w3.org/2001/XMLSchema"\r\n\t xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\r\n\t xsi:noNamespaceSchemaLocation="http://www.weather.gov/view/current_observation.xsd">\r\n\t<credit>NOAA's National Weather Service</credit>\r\n\t<credit_URL>http://weather.gov/</credit_URL>\r\n\t<image>\r\n\t\t<url>http://weather.gov/images/xml_logo.gif</url>\r\n\t\t<title>NOAA's National Weather Service</title>\r\n\t\t<link>http://weather.gov</link>\r\n\t</image>\r\n\t<suggested_pickup>15 minutes after the hour</suggested_pickup>\r\n\t<suggested_pickup_period>60</suggested_pickup_period>\n\t<location>Denton Enterprise Airport, TX</location>\n\t<station_id>KDTO</station_id>\n\t<latitude>33.20505</latitude>\n\t<longitude>-97.20061</longitude>\n\t<observation_time>Last Updated on Feb 16 2019, 7:53 pm CST</observation_time>\r\n        <observation_time_rfc822>Sat, 16 Feb 2019 19:53:00 -0600</observation_time_rfc822>\n\t<weather>Overcast</weather>\n\t<temperature_string>41.0 F (5.0 C)</temperature_string>\r\n\t<temp_f>41.0</temp_f>\r\n\t<temp_c>5.0</temp_c>\n\t<relative_humidity>82</relative_humidity>\n\t<wind_string>Southeast at 10.4 MPH (9 KT)</wind_string>\n\t<wind_dir>Southeast</wind_dir>\n\t<wind_degrees>140</wind_degrees>\n\t<wind_mph>10.4</wind_mph>\n\t<wind_kt>9</wind_kt>\n\t<pressure_string>1004.4 mb</pressure_string>\n\t<pressure_mb>1004.4</pressure_mb>\n\t<pressure_in>29.66</pressure_in>\n\t<dewpoint_string>36.0 F (2.2 C)</dewpoint_string>\r\n\t<dewpoint_f>36.0</dewpoint_f>\r\n\t<dewpoint_c>2.2</dewpoint_c>\n\t<windchill_string>35 F (2 C)</windchill_string>\r\n      \t<windchill_f>35</windchill_f>\r\n      \t<windchill_c>2</windchill_c>\n\t<visibility_mi>7.00</visibility_mi>\n \t<icon_url_base>http://forecast.weather.gov/images/wtf/small/</icon_url_base>\n\t<two_day_history_url>http://www.weather.gov/data/obhistory/KDTO.html</two_day_history_url>\n\t<icon_url_name>novc.png</icon_url_name>\n\t<ob_url>http://www.weather.gov/data/METAR/KDTO.1.txt</ob_url>\n\t<disclaimer_url>http://weather.gov/disclaimer.html</disclaimer_url>\r\n\t<copyright_url>http://weather.gov/disclaimer.html</copyright_url>\r\n\t<privacy_policy_url>http://weather.gov/notice.html</privacy_policy_url>\r\n</current_observation>\n
    """
  end
end

ExUnit.start()
